# version: '3.8'

services:
  api:
    build:
      context: code/deployment/api
    volumes:
      - ../models:/app/models  
    ports:
      - "8000:8000"

  app:
    build:
      context: code/deployment/app
    ports:
      - "8501:8501"
    depends_on:
      - api
